services:
  postgres:
    image: postgres:15
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Rodri68

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak_server
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: Rodri68
      KEYCLOAK_ADMIN: admiinfaantasy@gmail.com
      KEYCLOAK_ADMIN_PASSWORD: Rodri68
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak_imports:/opt/keycloak/data/import   
      - ./keycloak_providers:/opt/keycloak/providers
    expose:
      - "8080"
    depends_on:
      - postgres
    networks:
      - keycloak-network
    restart: unless-stopped


  # nginx:
  #   image: nginx:latest
  #   container_name: keycloak_nginx
  #   ports:
  #   - "8080:80"
  #   - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./certs:/etc/letsencrypt:ro
  #     - ./acme-challenge:/var/www/acme-challenge  # Séparé du dossier certs
  #   depends_on:
  #     - keycloak
  #   networks:
  #     - keycloak-network
  #   restart: unless-stopped

volumes:
  postgres_data:

networks:
  keycloak-network:
    driver: bridge