services:
  postgres:
    image: postgres:15
    container_name: keycloak_db
    ports:
     - "5432:5432"
    env_file:
      - keycloak.env
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    restart: unless-stopped

  keycloak:
  image: quay.io/keycloak/keycloak:24.0.1
  container_name: keycloak_server
  command: ["start-dev"]
  env_file:
    - keycloak.env
  environment:
    - QUARKUS_LOG_LEVEL=DEBUG
    - QUARKUS_LOG_CATEGORY__ORG_KEYCLOAK_THEME__LEVEL=TRACE
    - QUARKUS_LOG_CATEGORY__ORG_KEYCLOAK_FORMS__LEVEL=DEBUG
  ports:
    - "8180:8080"
  volumes:
    - ./keycloak_imports:/opt/keycloak/data/import
    - ./keycloak_exports:/opt/keycloak/data/export
    - ./keycloak_providers:/opt/keycloak/providers
    - ../mytheme:/opt/keycloak/themes/mytheme
  expose:
    - "8080"
  depends_on:
    - postgres
  networks:
    - keycloak-network
  restart: unless-stopped
  mysql:
    image: mysql:8
    container_name: mysql_fantasy
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fantasy_db
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - keycloak-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_fantasy
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - keycloak-network      

volumes:
  postgres_data:
  mysql_data:

networks:
  keycloak-network:
    driver: bridge
